namespace PokemonSaveFileEditor.Enums
{
    public enum Item : int
    {
        NONE = 0,
        MASTERBALL = 1,      // Catches any Pokémon without fail
        ULTRABALL = 2,       // High-performance Poké Ball
        GREATBALL = 3,       // Better than Poké Ball
        POKEBALL = 4,        // Standard Poké Ball
        TOWNMAP = 5,         // Displays the region map
        BICYCLE = 6,         // Faster movement
        SAFARIBALL = 8,      // Special ball for Safari Zone
        POKEDEX = 9,         // Electronic Pokémon encyclopedia
        MOONSTONE = 10,      // Evolves certain Pokémon
        ANTIDOTE = 11,       // Heals poison
        BURNHEAL = 12,       // Heals burn
        ICEHEAL = 13,        // Heals freeze
        AWAKENING = 14,      // Wakes a sleeping Pokémon
        PARLYZHEAL = 15,     // Heals paralysis
        FULLRESTORE = 16,    // Fully heals HP and status
        MAXPOTION = 17,      // Fully heals HP
        HYPERPOTION = 18,    // Heals 200 HP
        SUPERPOTION = 19,    // Heals 50 HP
        POTION = 20,         // Heals 20 HP
        BOULDERBADGE = 21,   // Badge from Pewter Gym
        CASCADEBADGE = 22,   // Badge from Cerulean Gym
        THUNDERBADGE = 23,   // Badge from Vermilion Gym
        RAINBOWBADGE = 24,   // Badge from Celadon Gym
        SOULBADGE = 25,      // Badge from Fuchsia Gym
        MARSHBADGE = 26,     // Badge from Saffron Gym
        VOLCANOBADGE = 27,   // Badge from Cinnabar Gym
        EARTHBADGE = 28,     // Badge from Viridian Gym
        ESCAPEROPE = 29,     // Escape from caves instantly
        REPEL = 30,          // Repels wild Pokémon (100 steps)
        OLDAMBER = 31,       // Fossil that revives Aerodactyl
        FIRESTONE = 32,      // Evolves certain Fire-types
        THUNDERSTONE = 33,   // Evolves certain Electric-types
        WATERSTONE = 34,     // Evolves certain Water-types
        HPUP = 35,           // Increases HP stat
        PROTEIN = 36,        // Increases Attack stat
        IRON = 37,           // Increases Defense stat
        CARBOS = 38,         // Increases Speed stat
        CALCIUM = 39,        // Increases Special stat
        RARECANDY = 40,      // Instantly raises level by 1
        DOMEFOSSIL = 41,     // Fossil that revives Kabuto
        HELIXFOSSIL = 42,    // Fossil that revives Omanyte
        SECRETKEY = 43,      // Opens Cinnabar Gym
        BIKEVOUCHER = 45,    // Exchange for a Bicycle
        XACCURACY = 46,      // Raises accuracy in battle
        LEAFSTONE = 47,      // Evolves certain Grass-types
        CARDKEY = 48,        // Opens doors in Silph Co.
        NUGGET = 49,         // Sell for high price
        PPUPSTAR = 50,       // Raises PP of a move
        POKEDOLL = 51,       // Escapes from wild battle
        FULLHEAL = 52,       // Heals all status problems
        REVIVE = 53,         // Revives a fainted Pokémon (half HP)
        MAXREVIVE = 54,      // Revives a fainted Pokémon (full HP)
        GUARDSPEC = 55,      // Prevents stat reduction
        SUPERREPEL = 56,     // Repels wild Pokémon (200 steps)
        MAXREPEL = 57,       // Repels wild Pokémon (250 steps)
        DIREHIT = 58,        // Increases critical hit ratio
        COIN = 59,           // Game Corner coin
        FRESHWATER = 60,     // Heals 50 HP
        SODAPOP = 61,        // Heals 60 HP
        LEMONADE = 62,       // Heals 80 HP
        SSTICKET = 63,       // Board the S.S. Anne
        GOLDTEETH = 64,      // Give to Warden for HM04
        XATTACK = 65,        // Raises Attack in battle
        XDEFEND = 66,        // Raises Defense in battle
        XSPEED = 67,         // Raises Speed in battle
        XSPECIAL = 68,       // Raises Special in battle
        COINCASE = 69,       // Holds Game Corner coins
        OAKSPARCEL = 70,     // Deliver to Prof. Oak
        ITEMFINDER = 71,     // Detects hidden items
        SILPHSCOPE = 72,     // Reveals Ghost Pokémon
        POKEFLUTE = 73,      // Wakes sleeping Pokémon
        LIFTKEY = 74,        // Operates elevator in Rocket Hideout
        EXPALL = 75,         // Shares EXP with all party Pokémon
        OLDROD = 76,         // Catches common Water Pokémon
        GOODROD = 77,        // Catches better Water Pokémon
        SUPERROD = 78,       // Catches rare Water Pokémon
        PPUP = 79,           // Raises PP of a move
        ETHER = 80,          // Restores 10 PP
        MAXETHER = 81,       // Restores all PP for one move
        ELIXER = 82,         // Restores 10 PP for all moves
        MAXELIXER = 83,      // Restores all PP for all moves

        // HMs
        HM01 = 196,          // Cut
        HM02 = 197,          // Fly
        HM03 = 198,          // Surf
        HM04 = 199,          // Strength
        HM05 = 200,          // Flash

        // TMs
        TM01 = 201,          // Mega Punch
        TM02 = 202,          // Razor Wind
        TM03 = 203,          // Swords Dance
        TM04 = 204,          // Whirlwind
        TM05 = 205,          // Mega Kick
        TM06 = 206,          // Toxic
        TM07 = 207,          // Horn Drill
        TM08 = 208,          // Body Slam
        TM09 = 209,          // Take Down
        TM10 = 210,          // Double-Edge
        TM11 = 211,          // BubbleBeam
        TM12 = 212,          // Water Gun
        TM13 = 213,          // Ice Beam
        TM14 = 214,          // Blizzard
        TM15 = 215,          // Hyper Beam
        TM16 = 216,          // Pay Day
        TM17 = 217,          // Submission
        TM18 = 218,          // Counter
        TM19 = 219,          // Seismic Toss
        TM20 = 220,          // Rage
        TM21 = 221,          // Mega Drain
        TM22 = 222,          // SolarBeam
        TM23 = 223,          // Dragon Rage
        TM24 = 224,          // Thunderbolt
        TM25 = 225,          // Thunder
        TM26 = 226,          // Earthquake
        TM27 = 227,          // Fissure
        TM28 = 228,          // Dig
        TM29 = 229,          // Psychic
        TM30 = 230,          // Teleport
        TM31 = 231,          // Mimic
        TM32 = 232,          // Double Team
        TM33 = 233,          // Reflect
        TM34 = 234,          // Bide
        TM35 = 235,          // Metronome
        TM36 = 236,          // Self-Destruct
        TM37 = 237,          // Egg Bomb
        TM38 = 238,          // Fire Blast
        TM39 = 239,          // Swift
        TM40 = 240,          // Skull Bash
        TM41 = 241,          // Softboiled
        TM42 = 242,          // Dream Eater
        TM43 = 243,          // Sky Attack
        TM44 = 244,          // Rest
        TM45 = 245,          // Thunder Wave
        TM46 = 246,          // Psywave
        TM47 = 247,          // Explosion
        TM48 = 248,          // Rock Slide
        TM49 = 249,          // Tri Attack
        Tm50 = 250           // Substitute
    }
}